In [3]:
import tensorflow as tf

In [4]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [13]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
print('a:',a)
print('b:',b)

a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [18]:
x = tf.constant((([1,2,3],[1,4,6],[3,5,6])))
y= tf.constant([4,5,6])
print('x:',a)
print('y:',b)

x: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
y: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [20]:
d=tf.subtract(a,b)
print("sub",d)


sub tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [21]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [22]:
d.numpy()

array([-3, -3, -3])

In [23]:
f=tf.divide(a,b)

In [24]:
print('divid',f)

divid tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [25]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [26]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [28]:
a_matrix=tf.constant(([2,3],[3,6]))
b_matrix=tf.constant(([3,8],[4,8]))
g=tf.matmul(a_matrix,b_matrix)
print('matrix multi',g)

matrix multi tf.Tensor(
[[18 40]
 [33 72]], shape=(2, 2), dtype=int32)
